[book]
authors = ["weiqiang333"]
language = "en"
multilingual = false
src = "docs-src"
title = "doumeng"

[build]
build-dir = "docs"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/weiqiang333/weiqiang333.github.io"
